#!/bin/bash

### BEGIN INIT INFO
# Provides:        scioncc
# Required-Start:  $network
# Required-Stop:   $network
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start/Stop SciON pycc
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

start() {
 bash /home/ubuntu/start_scion.sh
}

stop() {
 sh /home/ubuntu/stop_scion.sh
}

case $1 in
  start|stop) $1;;
  restart) stop; start;;
  *) echo "Run as $0 <start|stop|restart>"; exit 1;;
esac
